// <auto-generated />
namespace TaskManager.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class nullable_total_work : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(nullable_total_work));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031705012_nullable_total_work"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
