// <auto-generated />
namespace TaskManager.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class comment_timespan_nullable_ticks : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(comment_timespan_nullable_ticks));
        
        string IMigrationMetadata.Id
        {
            get { return "201801161619596_comment_timespan_nullable_ticks"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
