// <auto-generated />
namespace TaskManager.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class last_task_id : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(last_task_id));
        
        string IMigrationMetadata.Id
        {
            get { return "201805031526136_last_task_id"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
