// <auto-generated />
namespace TaskManager.Data.Context
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class fix_description : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(fix_description));
        
        string IMigrationMetadata.Id
        {
            get { return "201801121607321_fix_description"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
